grafana:
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: ${grafana_nodeport}
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      provider:
        allowUiUpdates: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  service:
    type: NodePort
    port: 9090
    targetPort: 9090
    nodePort: ${prometheus_nodeport}

alertmanager:
  service:
    type: NodePort
    port: 9093
    targetPort: 9093
    nodePort: ${alertmanager_nodeport}
