grafana:
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 30100
  defaultDashboardsEnabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  service:
    type: NodePort
    port: 9090
    targetPort: 9090
    nodePort: 30200
  hostNetwork: true

alertmanager:
  service:
    type: NodePort
    port: 9093
    targetPort: 9093
    nodePort: 30300
