AWSTemplateFormatVersion: '2010-09-09'
Description: GitHub OIDC Provider and IAM Role for TFLint AWS Plugin with ViewOnlyAccess

Parameters:
  GitHubRepository:
    Type: String
    Description: GitHub repository (ex. repo:<GitHub username>/<GitHub repository name>:ref:refs/heads/<branch name>)

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  GitHubActionsTFLintRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-tflint-readonly-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub ${GitHubRepository}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess

Outputs:
  RoleARN:
    Description: ARN of the created IAM Role for TFLint AWS Plugin
    Value: !GetAtt GitHubActionsTFLintRole.Arn
  
  Instructions:
    Description: Instructions for using the role in GitHub Actions
    Value: !Sub |
      1. Add the Role ARN as a GitHub Secret named AWS_ROLE_ARN
      2. The workflow will automatically use this role for TFLint AWS plugin deep_check