AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon Bedrock Knowledge Base with OpenSearch'

Parameters:
  OpenSearchDomainArn:
    Type: String
    Description: ARN of the OpenSearch domain
  
  S3BucketArn:
    Type: String
    Description: ARN of the S3 bucket containing the data
  
  S3RoleArn:
    Type: String
    Description: ARN of the IAM role for S3 access
  
  KnowledgeBaseRoleArn:
    Type: String
    Description: ARN of the IAM role for Knowledge Base access

Resources:
  BedrockKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: AWSDocumentationKnowledgeBase
      Description: Knowledge base for AWS documentation and custom content
      RoleArn: !Ref KnowledgeBaseRoleArn
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1
      StorageConfiguration:
        Type: OPENSEARCH_MANAGED_CLUSTER
        OpensearchServerlessConfiguration:
          CollectionArn: !Ref OpenSearchDomainArn
          VectorIndexName: bedrock-kb-index
          FieldMapping:
            VectorField: vector_field
            TextField: text
            MetadataField: metadata

  # S3 データソースは別のリソースとして定義
  BedrockDataSource:
    Type: AWS::Bedrock::DataSource
    Properties:
      Name: AWSDocumentationDataSource
      Description: S3 data source for AWS documentation
      KnowledgeBaseId: !Ref BedrockKnowledgeBase
      DataSourceConfiguration:
        Type: S3
        S3Configuration:
          BucketArn: !Ref S3BucketArn
          InclusionPrefixes:
            - docs/

Outputs:
  KnowledgeBaseId:
    Description: ID of the created Knowledge Base
    Value: !Ref BedrockKnowledgeBase
  
  DataSourceId:
    Description: ID of the created Data Source
    Value: !Ref BedrockDataSource