name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
filter-by-commitish: true
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐝 Bug Fixes'
    labels:
      - 'bug'
  - title: '🔧 Fixes'
    labels:
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'dependencies'
autolabeler:
  - label: 'feature'
    branch:
      - '/^feature\/.+/'
  - label: 'fix'
    branch:
      - '/^fix\/.+/'
  - label: 'bug'
    title:
      - '/(^|\s)(bug|バグ)(\s|$)/i'
    body:
      - '/(^|\s)(bug|バグ)(\s|$)/i'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'dependencies'
      - 'bug'
      - 'fix'
  default: patch
template: |
  ## Changes

  $CHANGES