AWSTemplateFormatVersion: '2010-09-09'
Description: GitHub OIDC Provider and IAM Role for GitHub Actions

Parameters:
  GitHubRepository:
    Type: String
    Description: GitHub repository (ex. repo:<GitHub username>/<GitHub repository name>:ref:refs/heads/<branch name>)

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  GitHubActionsCreateRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: 'Policy allowing iam:CreateRole action only for GitHub OIDC provider'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: iam:GetRole
            Resource: '*'
          - Effect: Allow
            Action: iam:GetRolePolicy 
            Resource: '*'
          - Effect: Allow
            Action: iam:CreateRole
            Resource: '*'
          - Effect: Allow
            Action: iam:AttachRolePolicy
            Resource: '*'
          - Effect: Allow
            Action: iam:PutRolePolicy
            Resource: '*'
          - Effect: Allow
            Action: iam:PassRole
            Resource: '*'
          - Effect: Allow
            Action: iam:DeleteRole
            Resource: '*'
          - Effect: Allow
            Action: iam:ListRoles
            Resource: '*'
          - Effect: Allow
            Action: iam:ListRolePolicies
            Resource: '*'
          - Effect: Allow
            Action: iam:ListAttachedRolePolicies
            Resource: '*'
          - Effect: Allow
            Action: iam:TagRole
            Resource: '*'
          - Effect: Allow
            Action: iam:GetPolicy
            Resource: '*'
          - Effect: Allow
            Action: iam:CreatePolicy
            Resource: '*'
          - Effect: Allow
            Action: iam:DeletePolicy
            Resource: '*'
          - Effect: Allow
            Action: iam:DeleteRolePolicy
            Resource: '*'
          - Effect: Allow
            Action: iam:DetachRolePolicy
            Resource: '*'
          - Effect: Allow
            Action: iam:ListPolicies
            Resource: '*'
          - Effect: Allow
            Action: iam:TagPolicy
            Resource: '*'
          - Effect: Allow
            Action: iam:ListInstanceProfilesForRole
            Resource: '*'

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-github-actions-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub ${GitHubRepository}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
        - !Ref GitHubActionsCreateRolePolicy

Outputs:
  RoleARN:
    Description: ARN of the created IAM Role
    Value: !GetAtt GitHubActionsRole.Arn
