AWSTemplateFormatVersion: '2010-09-09'
Description: 'SCP to enforce Owner tag on resource creation'

Parameters:
  PolicyName:
    Type: String
    Default: 'EnforceOwnerTagPolicy'
    Description: 'Name of the SCP policy'
  
  PolicyDescription:
    Type: String
    Default: 'Deny resource creation without Owner tag'
    Description: 'Description of the SCP policy'

  TargetIds:
    Type: CommaDelimitedList
    Default: ''
    Description: 'Comma-separated list of Organization Unit IDs or Account IDs to attach this policy to (optional)'

Conditions:
  HasTargets: !Not [!Equals [!Join ['', !Ref TargetIds], '']]

Resources:
  OwnerTagEnforcementPolicy:
    Type: AWS::Organizations::Policy
    Properties:
      Name: !Ref PolicyName
      Description: !Ref PolicyDescription
      Type: SERVICE_CONTROL_POLICY
      Content:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyAthenaWorkGroupCreationWithoutOwnerTag
            Effect: Deny
            Action: athena:CreateWorkGroup
            Resource: 'arn:aws:athena:*:*:workgroup/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyCloudTrailCreationWithoutOwnerTag
            Effect: Deny
            Action: cloudtrail:CreateTrail
            Resource: 'arn:aws:cloudtrail:*:*:trail/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyCloudWatchAlarmCreationWithoutOwnerTag
            Effect: Deny
            Action: cloudwatch:PutMetricAlarm
            Resource: 'arn:aws:cloudwatch:*:*:alarm:*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyElasticIPAllocationWithoutOwnerTag
            Effect: Deny
            Action: ec2:AllocateAddress
            Resource: 'arn:aws:ec2:*:*:elastic-ip/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyNATGatewayCreationWithoutOwnerTag
            Effect: Deny
            Action: ec2:CreateNatGateway
            Resource: 'arn:aws:ec2:*:*:natgateway/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyVPCEndpointCreationWithoutOwnerTag
            Effect: Deny
            Action: ec2:CreateVpcEndpoint
            Resource: 'arn:aws:ec2:*:*:vpc-endpoint/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyECSClusterCreationWithoutOwnerTag
            Effect: Deny
            Action: ecs:CreateCluster
            Resource: 'arn:aws:ecs:*:*:cluster/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyECSServiceCreationWithoutOwnerTag
            Effect: Deny
            Action: ecs:CreateService
            Resource: 'arn:aws:ecs:*:*:service/*/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyEFSCreationWithoutOwnerTag
            Effect: Deny
            Action: elasticfilesystem:CreateFileSystem
            Resource: 'arn:aws:elasticfilesystem:*:*:file-system/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyEKSClusterCreationWithoutOwnerTag
            Effect: Deny
            Action: eks:CreateCluster
            Resource: 'arn:aws:eks:*:*:cluster/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyOpenSearchDomainCreationWithoutOwnerTag
            Effect: Deny
            Action: es:CreateDomain
            Resource: 'arn:aws:es:*:*:domain/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyFSxCreationWithoutOwnerTag
            Effect: Deny
            Action: fsx:CreateFileSystem
            Resource: 'arn:aws:fsx:*:*:file-system/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyKMSKeyCreationWithoutOwnerTag
            Effect: Deny
            Action: kms:CreateKey
            Resource: 'arn:aws:kms:*:*:key/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyOpenSearchServerlessCollectionCreationWithoutOwnerTag
            Effect: Deny
            Action: aoss:CreateCollection
            Resource: 'arn:aws:aoss:*:*:collection/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyRDSInstanceCreationWithoutOwnerTag
            Effect: Deny
            Action: rds:CreateDBInstance
            Resource: 'arn:aws:rds:*:*:db:*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenySecretsManagerSecretCreationWithoutOwnerTag
            Effect: Deny
            Action: secretsmanager:CreateSecret
            Resource: 'arn:aws:secretsmanager:*:*:secret:*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyEC2InstanceCreationWithoutOwnerTag
            Effect: Deny
            Action:
              - ec2:RunInstances
            Resource:
              - 'arn:aws:ec2:*:*:instance/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenyVolumeCreationWithoutOwnerTag
            Effect: Deny
            Action:
              - ec2:CreateVolume
            Resource:
              - 'arn:aws:ec2:*:*:volume/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
          - Sid: DenySnapshotCreationWithoutOwnerTag
            Effect: Deny
            Action:
              - ec2:CreateSnapshot
            Resource:
              - 'arn:aws:ec2:*:*:snapshot/*'
            Condition:
              'Null':
                'aws:RequestTag/Owner': 'true'
                "aws:ResourceTag/Owner": "true"
      TargetIds: !If [HasTargets, !Ref TargetIds, !Ref 'AWS::NoValue']

Outputs:
  PolicyId:
    Description: 'The unique identifier of the SCP'
    Value: !Ref OwnerTagEnforcementPolicy
    Export:
      Name: !Sub '${AWS::StackName}-PolicyId'
  
  PolicyArn:
    Description: 'The Amazon Resource Name (ARN) of the policy'
    Value: !GetAtt OwnerTagEnforcementPolicy.Arn
    Export:
      Name: !Sub '${AWS::StackName}-PolicyArn'