AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for sending game information to Discord'

Parameters:
  OpenRouterApiKeyParam:
    Type: String
    Description: SSM Parameter Store name for OpenRouter API key
    Default: /game-info/openrouter-api-key
  
  DiscordWebhookUrlParam:
    Type: String
    Description: SSM Parameter Store name for Discord webhook URL
    Default: /game-info/discord-webhook-url
  
  ScheduleExpression:
    Type: String
    Description: Schedule expression for the EventBridge rule
    Default: cron(0 0 ? * SUN *)  # Every Sunday at midnight
  
  LambdaTimeout:
    Type: Number
    Description: Lambda function timeout in seconds
    Default: 30
    MinValue: 3
    MaxValue: 900
  
  LambdaMemorySize:
    Type: Number
    Description: Lambda function memory size in MB
    Default: 128
    MinValue: 128
    MaxValue: 10240

Resources:
  # IAM Role for Lambda function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${OpenRouterApiKeyParam}'
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${DiscordWebhookUrlParam}'

  # Lambda function
  GameInfoLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GameInfoToDiscordFunction
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemorySize
      Environment:
        Variables:
          OPENROUTER_API_KEY_PARAM: !Ref OpenRouterApiKeyParam
          DISCORD_WEBHOOK_URL_PARAM: !Ref DiscordWebhookUrlParam
      Code:
        ZipFile: |
          # This is a placeholder. The actual code will be uploaded during deployment.
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Placeholder function'
              }

  # EventBridge rule to trigger Lambda function
  GameInfoScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: GameInfoToDiscordSchedule
      Description: Schedule to trigger the game info Lambda function
      ScheduleExpression: !Ref ScheduleExpression
      State: ENABLED
      Targets:
        - Arn: !GetAtt GameInfoLambdaFunction.Arn
          Id: GameInfoLambdaTarget

  # Permission for EventBridge to invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GameInfoLambdaFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt GameInfoScheduleRule.Arn

Outputs:
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref GameInfoLambdaFunction
  
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt GameInfoLambdaFunction.Arn
  
  EventBridgeRuleName:
    Description: Name of the EventBridge rule
    Value: !Ref GameInfoScheduleRule