AWSTemplateFormatVersion: '2010-09-09'
Description: Bedrock Knowledge Base and Data Source for Web Crawler

Parameters:
  ProjectName:
    Type: String
    Description: プロジェクト名
  
  BedrockRoleArn:
    Type: String
    Description: BedrockがOpenSearchにアクセスするためのロールARN

  OpenSearchArn:
    Type: String
    Description: OpenSearchドメインのARN

  OpenSearchEndpoint:
    Type: String
    Description: OpenSearchドメインのエンドポイント

  AwsRegion:
    Type: String
    Description: AWSリージョン

  CrawlingUrls:
    Type: String
    Description: クロール対象のURLリスト（JSON形式）

Resources:
  BedrockKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: !Sub "${ProjectName}-kb"
      Description: Knowledge base for web crawler data
      KnowledgeBaseConfiguration: 
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          StorageConfiguration:
            Type: OPENSEARCH_MANAGED_CLUSTER
            OpenSearchManagedClusterConfiguration:
              FieldMapping:
                EmbeddingFieldName: embedding
                TextFieldName: text
                MetadataFieldNames:
                  - url
                  - title
              RoleArn: !Ref BedrockRoleArn
              Endpoint: !Sub "https://${OpenSearchEndpoint}"
              IndexName: bedrock-kb

  BedrockDataSource:
    Type: AWS::Bedrock::DataSource
    Properties:
      Name: !Sub "${ProjectName}-web-crawler"
      VectorIngestionConfiguration:
        KnowledgeBaseConfiguration:
          KnowledgeBaseId: !Ref BedrockKnowledgeBase
          ModelId: amazon.titan-embed-text-v2:0
        Schedule:
          Frequency: P7D
        Source:
          WebCrawler:
            Urls: !Ref CrawlingUrls
            MaxFileSize: 5000
            MaxTotalFiles: 1000
            UrlPatterns:
              AllowList:
                - "*"
            StorageConfiguration:
              Type: RETAIN

Outputs:
  KnowledgeBaseId:
    Description: Bedrock Knowledge Base ID
    Value: !Ref BedrockKnowledgeBase

  DataSourceId:
    Description: Bedrock Data Source ID
    Value: !Ref BedrockDataSource
