apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: myflask:v1.0
        command: ["/bin/bash"]
        args: ["-c", "FLASK_APP=run.py flask run --host=0.0.0.0"]
        ports:
          - containerPort: 5000
        envFrom:
        - secretRef:
            name: myflask
---
apiVersion: v1
kind: Service
metadata:
  name: myflask
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myflask
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /myflask
        pathType: Prefix
        backend:
          service:
            name: myflask
            port:
              number: 80
