apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: myflask:v1.0
        command: ["/bin/bash"]
        args: ["-c", "FLASK_APP=run.py flask run"]
        ports:
          - containerPort: 5000
        envFrom:
        - secretRef:
            name: myflask
