openapi: 3.0.3
info:
  title: API Gateway REST API
  description: |
    AWS API Gateway REST APIのサンプル実装
    
    このAPIは以下の機能を提供します：
    - ユーザー管理（作成、取得、一覧）
    - ヘルスチェック
    
    認証にはAPI Keyを使用します。
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://{api-id}.execute-api.ap-northeast-1.amazonaws.com/{stage}
    description: AWS API Gateway endpoint
    variables:
      api-id:
        default: example
        description: API Gateway REST API ID
      stage:
        default: dev
        description: Deployment stage
        enum:
          - dev
          - staging
          - prod

security:
  - ApiKeyAuth: []

x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params-only:
    validateRequestBody: false
    validateRequestParameters: true

# Components and paths will be merged from separate files
