apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch-data
spec:
  serviceName: "opensearch-data"
  replicas: 2
  selector:
    matchLabels:
      role: data
  template:
    metadata:
      labels:
        role: data
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.17.1
        ports:
        - containerPort: 9200
        resources:
          limits:
            cpu: "2"
            memory: "3Gi"
          requests:
            cpu: "300m"
            memory: "1Gi"
        lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - |
                  bin/opensearch-plugin install https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.17.1.0/prometheus-exporter-2.17.1.0.zip;
        env:
        - name: discovery.seed_hosts
          value: "opensearch-master-0.opensearch-master.default.svc.cluster.local,opensearch-master-1.opensearch-master.default.svc.cluster.local,opensearch-master-2.opensearch-master.default.svc.cluster.local,opensearch-data-0.opensearch-data.default.svc.cluster.local,opensearch-data-1.opensearch-data.default.svc.cluster.local"
        - name: cluster.initial_master_nodes
          value: "opensearch-master-0,opensearch-master-1,opensearch-master-2"
        - name: node.roles
          value: "data,ingest"
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          value: "Ospass123!"
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms256m -Xmx256m"
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-data
  labels:
    app: opensearch
spec:
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  clusterIP: None
  selector:
    role: data