AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !GetAtt 'MyAmi.AmazonLinux2'
      InstanceType: 't2.micro'
      KeyName: !Sub 'my-key-pair'
      SecurityGroups: [!Ref MySecurityGroup]

  MyAmi:
    Type: 'AWS::EC2::Image'
    Properties:
      Name: 'my-ami'
      Description: 'My Amazon Linux 2 AMI'
      ImageType: 'public'

  MyKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: !Sub 'my-key-pair'

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'My security group'
      VpcId: !GetAtt 'MyVPC.VpcId'
      SecurityGroupIngressRules:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'

  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'

Outputs:
  EC2InstancePublicDnsName:
    Value: !GetAtt MyEC2Instance.PublicDnsName
    Description: The public DNS name of the EC2 instance.