AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0c55b159cbfafe1f0'  # Using a direct AMI ID instead of !GetAtt
      InstanceType: 't2.micro'
      KeyName: 'my-key-pair'  # Fixed: Removed unnecessary !Sub
      SecurityGroupIds: [!Ref MySecurityGroup]  # Fixed: Using SecurityGroupIds instead of SecurityGroups

  # Removed AWS::EC2::Image resource as it's not a valid CloudFormation resource type

  MyKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: 'my-key-pair'  # Fixed: Removed unnecessary !Sub

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'My security group'
      VpcId: !Ref 'MyVPC'  # Fixed: Using !Ref instead of !GetAtt
      SecurityGroupIngress:  # Fixed: Using SecurityGroupIngress instead of SecurityGroupIngressRules
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'

  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'

Outputs:
  EC2InstancePublicDnsName:
    Value: !GetAtt MyEC2Instance.PublicDnsName
    Description: The public DNS name of the EC2 instance.