AWSTemplateFormatVersion: '2010-09-09'
Description: Bedrock Knowledge Base and Data Source for Web Crawler

Parameters:
  ProjectName:
    Type: String
    Description: プロジェクト名
  
  BedrockRoleArn:
    Type: String
    Description: BedrockがOpenSearchにアクセスするためのロールARN

  OpenSearchArn:
    Type: String
    Description: OpenSearchドメインのARN

  OpenSearchEndpoint:
    Type: String
    Description: OpenSearchドメインのエンドポイント

  AwsRegion:
    Type: String
    Description: AWSリージョン
    
  BedrockModelArn:
    Type: String
    Description: BedrockのEmbeddingモデルARN

Resources:
  BedrockKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: !Sub "${ProjectName}-kb"
      Description: Knowledge base for web crawler data
      RoleArn: !Ref BedrockRoleArn
      KnowledgeBaseConfiguration: 
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Sub "arn:aws:bedrock:${AwsRegion}::foundation-model/${BedrockModelArn}"
      StorageConfiguration:
        Type: OPENSEARCH_MANAGED_CLUSTER
        OpensearchManagedClusterConfiguration:
          DomainArn: !Ref OpenSearchArn
          DomainEndpoint: !Sub "https://${OpenSearchEndpoint}"
          VectorIndexName: blog-index
          FieldMapping:
            MetadataField: metadata
            TextField: text
            VectorField: blog-vector

Outputs:
  KnowledgeBaseId:
    Description: Bedrock Knowledge Base ID
    Value: !Ref BedrockKnowledgeBase

  DataSourceId:
    Description: Bedrock Data Source ID
    Value: "hoge"
