---
- hosts: localhost
  tasks:
  - name: create vpc
    ec2_vpc_net:
      name: "ansible-vpc-test"
      cidr_block: "10.0.0.0/16"
      region: "ap-northeast-1"
      tenancy: default
    register: vpc_net