AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon Q Developer in Slack Chat Applications'

Parameters:
  SlackWorkspaceId:
    Type: String
    Description: The ID of the Slack workspace authorized with AWS Chatbot
    
  SlackChannelId:
    Type: String
    Description: The ID of the Slack channel where Amazon Q Developer will be used
    
  SlackChannelName:
    Type: String
    Description: The name of the Slack channel where Amazon Q Developer will be used

Resources:
  # IAM Policy for CloudWatch read access
  AmazonQDeveloperInSlackPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: IAMP-amazon-q-developer-in-slack
      Description: Policy for Amazon Q Developer in Slack
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - chatbot:DescribeSlackChannelConfigurations
            Resource: '*'

  # IAM Role for Amazon Q Developer in Slack
  AmazonQDeveloperInSlackRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IAMR-amazon-q-developer-in-slack
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: chatbot.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref AmazonQDeveloperInSlackPolicy
        - arn:aws:iam::aws:policy/AmazonQDeveloperAccess
        - arn:aws:iam::aws:policy/ReadOnlyAccess

  # Slack Channel Configuration for Amazon Q Developer
  SlackChannelConfiguration:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName: !Sub AmazonQDeveloperSlackConfig-${SlackChannelName}
      IamRoleArn: !GetAtt AmazonQDeveloperInSlackRole.Arn
      SlackWorkspaceId: !Ref SlackWorkspaceId
      SlackChannelId: !Ref SlackChannelId
      
      GuardrailPolicies:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonQDeveloperAccess
      UserRoleRequired: false

Outputs:
  SlackChannelConfigurationArn:
    Description: ARN of the Slack Channel Configuration
    Value: !Ref SlackChannelConfiguration
  
  IAMRoleArn:
    Description: ARN of the IAM Role for Amazon Q Developer in Slack
    Value: !GetAtt AmazonQDeveloperInSlackRole.Arn