apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/server-snippets: |
      location / {
          return 200 $host;
      }
spec:
  tls:
  - hosts:
    - "mynginx[1-3].com"
    secretName: nginx
  ingressClassname: nginx
  rules:
  - host: "mynginx[1-3].com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx
            port:
              number: 443
