name: Ansible Linter

permissions:
  contents: write

on:
  push:
    branches-ignore:
      - main
    paths:
      - "**/ansible/**"

jobs:
  lint:
    name: Lint Ansible Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r .github/requirements.yml -p ./collections --force

      - name: Run ansible-lint
        uses: ansible/ansible-lint@665d9e07a1943254d2910faffc106adaf7ea7294 # v26.8.0
        # optional (see below):
        with:
          args: "--fix **/ansible/"
          setup_python: "true"
          working_directory: ""
          requirements_file: ".github/requirements.yml"

      - name: Check for changes
        if: ${{ !cancelled() }}
        id: git_diff
        run: |
          git add .
          git diff --cached --quiet && echo 'changes=' >> "$GITHUB_OUTPUT" || echo 'changes=changes' >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        if: ${{ steps.git_diff.outputs.changes == 'changes' && !cancelled() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Changes by ansible-lint actions"
          git push origin HEAD
