name: Ansible Linter

permissions:
  contents: write
  pull-requests: write

on:
  push:
    paths:
      - "**/ansible/**"

jobs:
  lint:
    name: Lint Ansible Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r .github/requirements.yml -p ./collections --force

      - name: Run ansible-lint
        uses: ansible/ansible-lint@8ba9595a4acd1b906eb75568b34f6ef592cd1528 # v26.3.0
        # optional (see below):
        with:
          args: "--fix **/ansible/"
          setup_python: "true"
          working_directory: ""
          requirements_file: ".github/requirements.yml"

      - name: Check for changes
        if: ${{ !cancelled() }}
        id: git_diff
        run: |
          git add .
          git diff --cached --quiet && echo 'changes=' >> "$GITHUB_OUTPUT" || echo 'changes=changes' >> "$GITHUB_OUTPUT"

      - name: Get current branch name
        if: ${{ steps.git_diff.outputs.changes == 'changes' && !cancelled() }}
        id: get_branch
        run: |
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        if: ${{ steps.git_diff.outputs.changes == 'changes' && !cancelled() }}
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ steps.get_branch.outputs.branch_name }}
          branch: ansible-lint-pr-${{ steps.get_branch.outputs.branch_name }}
          title: "Changes by ansible-lint actions"
          labels: fix
