name: CloudFormation Linter

on:
  push:
    paths:
      - "**/cfn/**/*.yaml"

permissions:
  contents: read

jobs:
  cfn-lint:
    name: CloudFormation Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: CloudFormation Linter
        uses: scottbrenner/cfn-lint-action@c5f18dc4be13042d564f3052f4067dc9ceafe355 # v2.7.0
        with:
          command: cfn-lint **/cfn/**/*.yaml
