name: CloudFormation Linter

on:
  push:
    paths:
      - "**/cfn/**/*.yaml"

permissions:
  contents: read

jobs:
  cfn-lint:
    name: CloudFormation Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: CloudFormation Linter
        uses: scottbrenner/cfn-lint-action@8affffc34dddd6937bbc37f60901f71657e20fab # v2.8.0
        with:
          command: cfn-lint **/cfn/**/*.yaml
