name: CloudFormation linter and PR

permissions:
  contents: write

on:
  push:
    branches-ignore:
      - main

jobs:
  cfn-linter:
    runs-on: ubuntu-latest
    outputs:
      linted: ${{ steps.run_linter.outputs.linted }}
      changes: ${{ steps.git_diff.outputs.changes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@ed184e91f5085a2932501da8314e899e5e0ef5be # v2.7.1

      - name: Print the Cloud Formation Linter Version & run Linter.
        id: run_linter
        run: |
          cfn-lint --version

          shopt -s globstar # enable globbing
          files=$(ls ./**/cfn/**/*.yaml ./**/cfn/**/*.yml 2>/dev/null || true)
          [ -n "${files}" ] && out=$(cfn-lint -t "$files" --non-zero-exit-code none -f parseable)
          if [ -n "${out}" ];then
            echo "${out}" | tee /tmp/cfn-lint-output.txt
            echo "linted=linted" >> "$GITHUB_OUTPUT"
          fi

      - name: Install and Run Ollama
        if: steps.run_linter.outputs.linted == 'linted'
        run: |
          cat /tmp/cfn-lint-output.txt | cut -d':' -f1 | sort | uniq | while read -r f;do
            echo -n "" > /tmp/input.txt

            {
              cat "$f"
              echo
              echo "---"
              echo
              grep "$f" /tmp/cfn-lint-output.txt
              echo
              echo "---"
              echo
              echo "Create a fixed cloudformation yaml file"
            } >> /tmp/input.txt

            if ! command -v ollama 1>/dev/null;then
              curl -fsSL https://ollama.com/install.sh | sh
            fi
            sleep 5
            cat /tmp/input.txt | ollama run llama3.2 | tee /tmp/output.txt
            sed -n '/```/,/```/p' /tmp/output.txt | sed '1d;$d' > "$f"
          done

      - name: Check for changes
        id: git_diff
        run: |
          git add .
          git diff --cached --quiet && echo 'changes=' >> "$GITHUB_OUTPUT" || echo 'changes=changes' >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        if: steps.git_diff.outputs.changes == 'changes' && !cancelled()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Changes by cfn-lint actions"
          git push origin HEAD
