name: CloudFormation Linter

on:
  push:
    paths:
      - "**/cfn/**/*.yaml"

permissions:
  contents: read

jobs:
  cfn-lint:
    name: CloudFormation Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: CloudFormation Linter
        uses: scottbrenner/cfn-lint-action@9636da81fb2e0cef75725d8dda11b0148940b7ae # v2.6.0
        with:
          command: cfn-lint **/cfn/**/*.yaml
