name: Compile Agentic Workflow

permissions:
  contents: write

on:
  push:
    paths:
      - ".github/workflows/*.md"
    branches-ignore:
      - main

jobs:
  compile-agentic-workflow:
    name: Compile Agentic Workflow Markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Install gh aw extension
        run: gh extension install github/gh-aw
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Compile Agentic Workflows
        run: gh aw compile
        working-directory: .github/workflows
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Check for changes
        if: ${{ !cancelled() }}
        id: git_diff
        run: |
          git add .
          git diff --cached --quiet && echo 'changes=' >> "$GITHUB_OUTPUT" || echo 'changes=changes' >> "$GITHUB_OUTPUT"

      - name: Push changes
        if: ${{ steps.git_diff.outputs.changes == 'changes' && !cancelled() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Changes by compile-agentic-workflow action"
          git push
