name: Dependency Review

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Dependency Review
        uses: actions/dependency-review-action@5f5e27c852bf4ce214d3cf753ed4e0c0b595455d # v4
