name: GitHub Actions Linter

permissions:
  contents: read

on:
  push:
    paths:
      - '.github/workflows/**'

jobs:
  lint:
    name: Lint GitHub Actions YAML Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: Lint GitHub Actions YAML Files
        uses: github/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Only validate new or edited files
          VALIDATE_ALL_CODEBASE: false
          # Only validate YAML and GitHub Actions files
          VALIDATE_YAML: true
          VALIDATE_GITHUB_ACTIONS: true
          # Filter for only GitHub Actions workflow files
          FILTER_REGEX_INCLUDE: .*github/workflows/.*