name: npm Unit Test

on:
  pull_request:
    paths:
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/npm-unit-test.yml"
  push:
    branches:
      - main
    paths:
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/npm-unit-test.yml"

permissions:
  contents: read

jobs:
  npm-unit-test:
    name: npm Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit