name: Terraform Apply Manual Test

on:
  workflow_dispatch:
    inputs:
      working-directory:
        description: 'Directory containing Terraform files'
        required: true
        type: string
      branch:
        description: 'Branch to checkout'
        required: true
        type: string
        default: 'main'

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-northeast-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      
    - name: Terraform Init
      id: init
      working-directory: ${{ github.event.inputs.working-directory }}
      run: terraform init
      
    - name: Terraform Plan
      id: plan
      working-directory: ${{ github.event.inputs.working-directory }}
      run: terraform plan -no-color
      
    - name: Terraform Apply
      id: apply
      if: steps.plan.outcome == 'success'
      working-directory: ${{ github.event.inputs.working-directory }}
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      if: always()
      working-directory: ${{ github.event.inputs.working-directory }}
      run: terraform destroy -auto-approve

    - name: Check Apply Status
      if: steps.apply.outcome == 'failure'
      run: exit 1
