name: Terraform linter and PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.git_diff.outputs.changes }}
      branch: ${{ steps.create_branch.outputs.branch }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Format Terraform files
      run: terraform fmt -recursive

    - uses: actions/cache@v4
      name: Cache plugin dir for TFLint
      with:
        path: ~/.tflint.d/plugins
        key: ubuntu-latest-tflint-${{ hashFiles('.github/.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        tflint_version: "latest"

    - name: Configure AWS credentials
      id: aws-credentials
      if: ${{ secrets.AWS_ROLE_ARN != '' }}
      uses: aws-actions/configure-aws-credentials@v4
      continue-on-error: true
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1
        role-session-name: GithubActionsSession

    - name: Run TFLint with AWS plugin
      if: steps.aws-credentials.outcome == 'success' && steps.aws-credentials.conclusion == 'success'
      run: tflint --recursive -f compact --fix --minimum-failure-severity=warning --config=.github/.tflint.hcl

    - name: Run TFLint without AWS plugin
      if: steps.aws-credentials.outcome != 'success' || steps.aws-credentials.conclusion != 'success'
      run: tflint --recursive -f compact --fix --minimum-failure-severity=warning

    - name: Check for changes
      if: ${{ !cancelled() }}
      id: git_diff
      run: |
        git diff --exit-code && echo 'changes=' >> $GITHUB_OUTPUT || echo 'changes=changes' >> $GITHUB_OUTPUT

    - name: Create Pull Request
      if: steps.git_diff.outputs.changes == 'changes' && ${{ !cancelled() }}
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: main
        branch: tflint-pr
        title: "Changes by tflint actions"
