name: Terraform linter and PR

on:
  push:
    paths:
      - "**/*.tf"

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.git_diff.outputs.changes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Format Terraform files
        run: terraform fmt -recursive

      - uses: actions/cache@v4
        name: Cache plugin dir for TFLint
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.github/.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v6
        name: Setup TFLint
        with:
          tflint_version: "latest"

      - name: Check if AWS Role ARN is available
        id: check_role
        run: |
          if [ -n "${{ secrets.AWS_ROLE_ARN }}" ]; then
            echo "aws_role_available=true" >> "$GITHUB_OUTPUT"
          else
            echo "aws_role_available=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Configure AWS Credentials
        if: steps.check_role.outputs.aws_role_available == 'true'
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
          mask-aws-account-id: true

      - name: Run TFLint with AWS plugin
        if: steps.check_role.outputs.aws_role_available == 'true'
        run: |
          tflint --init --config="${GITHUB_WORKSPACE}/.github/.tflint.hcl"
          tflint --recursive -f compact --fix --minimum-failure-severity=warning --config="${GITHUB_WORKSPACE}/.github/.tflint.hcl"

      - name: Run TFLint without AWS plugin
        if: steps.check_role.outputs.aws_role_available == 'false'
        run: tflint --recursive -f compact --fix --minimum-failure-severity=warning

      - name: Check for changes
        if: ${{ !cancelled() }}
        id: git_diff
        run: |
          git add .
          git diff --cached --quiet && echo 'changes=' >> "$GITHUB_OUTPUT" || echo 'changes=changes' >> "$GITHUB_OUTPUT"

      - name: Get current branch name
        if: steps.git_diff.outputs.changes == 'changes' && ${{ !cancelled() }}
        id: get_branch
        run: |
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        if: steps.git_diff.outputs.changes == 'changes' && ${{ !cancelled() }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ steps.get_branch.outputs.branch_name }}
          branch: tflint-pr-${{ steps.get_branch.outputs.branch_name }}
          title: "Changes by tflint actions"
